print(True and True,
        True and False,
        1 == 1 and 2 == 1,
        "test" == "test",
        1 == 1 and 2 != 1,
        True and 1 == 1,
        "test" == "testing",
        1 != 0 and 2 == 1,
        "test" != "testing",
        "test" == 1,
        not (True and False),
        not (1 == 1 and 0!= 1),
        not (100 == 10 and 1000 == 1000),
        not ( 1 != 10 or 40 == 30),
        not ("testing" == "testing" and "zed" == "cool"),
        1 == 1 and not (1==1 or 1==0),
        "chunky" == "bacon" and (not(3==4)),
        "this" == "is" and "not" == "cool")
